version: '3'
services:
  app:
    image: nginx
    container_name: nginx
    ports:
#8081
      - '8081:8081'
    volumes:
      - "./nginx-proxy.conf:/etc/nginx/nginx.conf:ro"
#sudo docker run -p 8081:8081 -v ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro --name nginx nginx
