version: '3'
services:
  app:
    image: nginx
#    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx
    ports:
#       - '8081:8081'
      - '80:8081'
    volumes:
      - "./nginx-proxy.conf:/etc/nginx/nginx.conf:ro"
