version: '3'
services:
  app:
    image: nginx
    contain er_name: nginx
    ports:
#8081
      - '8081:8081'
    volumes:
      - "./nginx-proxy.conf:/etc/nginx/nginx.conf:ro"
#sudo docker run -p 8081:8081 -v /home/ec2-user/nginx-proxy.conf:/etc/nginx/nginx.conf:ro -detach --name nginx nginx

