pipeline {
    agent any 
    stages {
        stage ("verify tooling") {
            steps {
            ssh '''
            docker version
            docker info
            docker compose version
            curl --version
            jq --version
            '''
            }
        }
        stage('Prune Docker data')
        steps {
            sh 'docker system prune -a volumes -f'
        }
    }
}