pipeline {
    agent any 
    stages {
        stage ("verify tooling") {
            steps {
            ssh '''
            docker version
            docker info
            docker compose version
            curl --version
            jq --version
            '''
            }
        }
        
    }
}